name: Daily Export

on:
  schedule:
    - cron: '0 0 * * *' # UTC 00:00 = jam 07:00 WIB
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Inject .env from Secrets
        run: |
          echo "BIGSELLER_EMAIL=${{ secrets.BIGSELLER_EMAIL }}" >> .env
          echo "BIGSELLER_PASSWORD=${{ secrets.BIGSELLER_PASSWORD }}" >> .env

      - name: Run Export Script
        run: npm start
